### ISSUE TITLE
Check if a variable declaration is static

### ISSUE THREAD

**Issue by zimmski** [sbinet/go-clang#13]
I am wondering how I can check if a variable declaration (Type == VarDecl) is static. There is method called "isStaticLocal" in the Clang documentation http://clang.llvm.org/doxygen/classclang_1_1VarDecl.html#a513c56596b4d12e99dd42a4f3ff646d4 but I do not see it in go-clang.

How can I add and use isStaticLocal in go-clang? Can you please document the steps of enhancing go-clang so that I can do it on my own, and send pull request. I am currently a little baffled on how to do that.

**Comment by zimmski** [comment]
I guess this was added with https://github.com/llvm-mirror/clang/commit/763069ac81d376e544b40a844a70e5e984e10bf4 but unfortunately it looks like my clang-c version is too old.

**Comment by sbinet** [comment]
yes, once your clang-c install is up to date, you'd then have to create a `StorageClass` (like the `AvailabilityKind` one) and define the methods on it. (if I am reading the py-cindex code correctly)

**Comment by zimmski** [comment]
We are in the process of upgrading our LLVM version (to 3.6.x) and since go-clang is part of our system I am meaning to ask if you have a script to automate the API creation process? Also, would it make sense to create and maintain branches of go-clang for the different LLVM versions? Since when I add the StorageClass type to the API I cannot compile it with an older LLVM version.
In short: I am willing to do some of the maintainer work if you like, but I would prefer it if most of the go-clang code would be generated so that handling new versions of LLVM is not that time consuming.

**Comment by sbinet** [comment]
unfortunately, no, I don't have such a script.
ideally, one would just have to use `go-clang` to parse the `clang-cindex` C-API and generate stubs for `go-clang`... or use the `python` bindings?

wrt the different `LLVM` versions, I did create a few branches, but not very consistently:

```sh
$ git branch -l -r
  origin/HEAD -> origin/master
  origin/dev/clang-3.2
  origin/master
  origin/release/clang-3.0
  origin/release/clang-3.2
  origin/release/clang-3.4
```

in retrospect, investing some effort into an infrastructure that can `go generate` a good chunk of the `go-clang` code would be indeed desirable...

**Comment by sbinet** [comment]
one more thing (thinking out loud): perhaps use `gopkg.in` for the multiversion handling of the `C-API`.
see #14.

**Comment by zimmski** [comment]
Yes, I noticed the branches but they looked to me like they were branched of along the way. I am thinking of doing branches that always originate from a "generate" branch:
- Create logic to automate the API generation process in the "generate" branch
- Generate for LLVM version x.y.z
- Put the result in branch x.y

The logic to keep the branches up to date would then be:
- LLVM update: Regenerate the according branch
- Update to the API generating code: Regenerate all branches

The master branch would then always hold the version for the latest stable LLVM version.

This would be an enormous initial effort but would drop the maintaining time to almost zero while still supporting new LLVM versions.

**Comment by sbinet** [comment]
SGTM

**Comment by sbinet** [comment]
Just filed #15 to track this particular `go generate` issue.

**Comment by zimmski** [comment]
I never used gopkg.in but it seems to me that branch and tag names have to be in the correct format to make it work. Maybe a release process could be written down e.g. branch major versions of LLVM and tag minor versions in the branches of the major versions?

**Comment by sbinet** [comment]
that could be the modus operandi.

**Comment by zimmski** [comment]
So the original intention of this issue was to find out how to see if a variable is static. Well that can be done with:

``` go
package main

import (
    "fmt"

    "github.com/go-clang/v3.7/clang"
)

func main() {
    idx := clang.NewIndex(0, 1)
    defer idx.Dispose()

    tu := idx.ParseTranslationUnit("tt.c", nil, nil, 0)
    defer tu.Dispose()

    cursor := tu.TranslationUnitCursor()

    cursor.Visit(func(cursor, parent clang.Cursor) clang.ChildVisitResult {
        if cursor.IsNull() {
            return clang.ChildVisit_Continue
        }

        switch cursor.Kind() {
        case clang.Cursor_VarDecl:
            fmt.Printf("Variable %s is %s\n", cursor.Spelling(), cursor.StorageClass().Spelling())

            if cursor.StorageClass() == clang.SC_Static {
                fmt.Println("\tYep, its static")
            }
        }

        return clang.ChildVisit_Recurse
    })
}
```

This C file

``` c
#include <stdio.h>

void up() {
    static int i = 0;
    int j = 0;

    i++;
    j++;

    printf("%d vs %d\n", i, j);
}
```

Prints

```
Variable _IO_2_1_stdin_ is SC=Extern
Variable _IO_2_1_stdout_ is SC=Extern
Variable _IO_2_1_stderr_ is SC=Extern
Variable stdin is SC=Extern
Variable stdout is SC=Extern
Variable stderr is SC=Extern
Variable sys_nerr is SC=Extern
Variable sys_errlist is SC=Extern
Variable i is SC=Static
        Yep, its static
Variable j is SC=None
```

So let's finally close this issue ;-)
