### ISSUE TITLE
Better default LD path for darwin.

### ISSUE THREAD

**Issue by dzan** [sbinet/go-clang#16]
On all (developer) OSX systems I think this would be a more sane default;

    #cgo darwin LDFLAGS: -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib

The previous value would be the one to use when you install clang yourself I think?

**Comment by zimmski** [comment]
We kind of fixed this in the https://github.com/go-clang repositories by querying "llvm-config" instead of hardcoding a path, e.g., https://github.com/go-clang/v3.7/blob/master/Makefile#L13 so your problem should be fixed there.

**Comment by sbinet** [comment]
yes. please use `go-clang` from [github.com/go-clang](https://github.com/go-clang)
